name: flashlights_client
description: Remote torch/audio client for Flashlights-in-the-Dark
publish_to: 'none'
version: 1.0.0+1

environment:
  # Works with Flutter 3.19 + and Dart 3.7 +
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- runtime plugins ---
  cupertino_icons: ^1.0.8
  osc: ^1.0.0          # Open-Sound-Control packets
  torch_light: ^1.1.0  # Flash/torch control (on/off only – no brightness)
  just_audio: ^0.9.37  # Audio playback
  mic_stream: ^0.7.2   # Raw mic samples/recording
  permission_handler: ^11.4.0  # camera / mic permissions (iOS / Android only)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # latest lint set for Dart 3

flutter:
  uses-material-design: true
