name: flashlights_client
description: Remote torch/audio client for Flashlights-in-the-Dark
publish_to: 'none'
version: 1.0.1+4

environment:
  # Works with Flutter 3.19 + and Dart 3.7 +
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- runtime plugins ---
  cupertino_icons: ^1.0.8
  torch_light: ^1.1.0  # Flash/torch control (on/off only – no brightness)
  screen_brightness: ^2.1.5 # Control screen brightness for strobe dimming
  just_audio: ^0.10.4  # Audio playback
  audio_session: ^0.1.21 # Ensure playback works in silent mode on iOS/Android
  permission_handler: ^11.4.0  # camera / mic permissions (iOS / Android only)
  wakelock_plus: ^1.2.5     # Keep the screen awake during performances
  shared_preferences: ^2.5.3  # Persist selected slot between launches

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # latest lint set for Dart 3

flutter:
  uses-material-design: true
  assets:
    - available-sounds/

dependency_overrides:
  win32: ^5.14.0

flutter_icons:
  android: true
  ios: false
  image_path: FlashlightsInTheDark_Icons/FlashlightsInTheDark-Icon-1024.png
