name: flashlights_client
description: Remote torch/audio client for Flashlights-in-the-Dark
publish_to: 'none'
version: 1.0.0+1

environment:
  # Works with Flutter 3.19 + and Dart 3.7 +
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- runtime plugins ---
  cupertino_icons: ^1.0.8
  torch_light: ^1.1.0  # Flash/torch control (on/off only – no brightness)
  screen_brightness: ^2.1.5 # Control screen brightness for strobe dimming
  just_audio: ^0.10.4  # Audio playback
  mic_stream: ^0.7.2   # Raw mic samples/recording
  permission_handler: ^11.4.0  # camera / mic permissions (iOS / Android only)
  wakelock: ^0.6.2     # Keep the screen awake during performances
  wakelock_windows: ^0.2.1
  shared_preferences: ^2.5.3  # Persist selected slot between launches

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # latest lint set for Dart 3

flutter:
  uses-material-design: true
  assets:
    - available-sounds/

dependency_overrides:
  win32: ^5.14.0
