name: flashlights_client
description: Remote torch/audio client for Flashlights-in-the-Dark
publish_to: 'none'
version: 1.0.3+6

environment:
  # Works with Flutter 3.19 + and Dart 3.7 +
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- runtime plugins ---
  cupertino_icons: ^1.0.8
  torch_light: ^1.1.0  # Flash/torch control (on/off only – no brightness)
  screen_brightness: ^2.1.5 # Control screen brightness for strobe dimming
  audio_session: ^0.1.25 # Ensure playback works in silent mode on iOS/Android
  # Primer tones are played using native audio implementations via method channels.
  permission_handler: ^11.4.0  # camera / mic permissions (iOS / Android only)
  wakelock_plus: ^1.2.5     # Keep the screen awake during performances
  shared_preferences: ^2.5.3  # Persist selected slot between launches
  webview_flutter: ^4.7.0  # Embed OSMD via WebView
  xml: ^6.5.0  # Parse and trim MusicXML assets
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # latest lint set for Dart 3

flutter:
  uses-material-design: true
  assets:
    - assets/event_recipes.json
    - assets/FlashlightsInTheDark_SingerScore23.musicxml
    - assets/osmd_view.html
    - assets/opensheetmusicdisplay.min.js
    # Primer tone library (explicit listing avoids wildcard bundling gaps on iOS)
    - available-sounds/primerTones/Long50.mp3
    - available-sounds/primerTones/Long51.mp3
    - available-sounds/primerTones/Long52.mp3
    - available-sounds/primerTones/Long53.mp3
    - available-sounds/primerTones/Long54.mp3
    - available-sounds/primerTones/Long55.mp3
    - available-sounds/primerTones/Long56.mp3
    - available-sounds/primerTones/Long57.mp3
    - available-sounds/primerTones/Long58.mp3
    - available-sounds/primerTones/Long59.mp3
    - available-sounds/primerTones/Long60.mp3
    - available-sounds/primerTones/Long61.mp3
    - available-sounds/primerTones/Long62.mp3
    - available-sounds/primerTones/Long63.mp3
    - available-sounds/primerTones/Long64.mp3
    - available-sounds/primerTones/Long65.mp3
    - available-sounds/primerTones/Long66.mp3
    - available-sounds/primerTones/Long67.mp3
    - available-sounds/primerTones/Long68.mp3
    - available-sounds/primerTones/Long69.mp3
    - available-sounds/primerTones/Long70.mp3
    - available-sounds/primerTones/Long71.mp3
    - available-sounds/primerTones/Long72.mp3
    - available-sounds/primerTones/Long73.mp3
    - available-sounds/primerTones/Long74.mp3
    - available-sounds/primerTones/Long75.mp3
    - available-sounds/primerTones/Long76.mp3
    - available-sounds/primerTones/Long77.mp3
    - available-sounds/primerTones/Long78.mp3
    - available-sounds/primerTones/Long79.mp3
    - available-sounds/primerTones/Long80.mp3
    - available-sounds/primerTones/Long81.mp3
    - available-sounds/primerTones/Long82.mp3
    - available-sounds/primerTones/Long83.mp3
    - available-sounds/primerTones/Long84.mp3
    - available-sounds/primerTones/Long85.mp3
    - available-sounds/primerTones/Long86.mp3
    - available-sounds/primerTones/Long87.mp3
    - available-sounds/primerTones/Long88.mp3
    - available-sounds/primerTones/Long89.mp3
    - available-sounds/primerTones/Long90.mp3
    - available-sounds/primerTones/Long91.mp3
    - available-sounds/primerTones/Long92.mp3
    - available-sounds/primerTones/Long93.mp3
    - available-sounds/primerTones/Long94.mp3
    - available-sounds/primerTones/Long95.mp3
    - available-sounds/primerTones/Long96.mp3
    - available-sounds/primerTones/Long97.mp3
    - available-sounds/primerTones/Long98.mp3
    - available-sounds/primerTones/Short0.mp3
    - available-sounds/primerTones/Short1.mp3
    - available-sounds/primerTones/Short2.mp3
    - available-sounds/primerTones/Short3.mp3
    - available-sounds/primerTones/Short4.mp3
    - available-sounds/primerTones/Short5.mp3
    - available-sounds/primerTones/Short6.mp3
    - available-sounds/primerTones/Short7.mp3
    - available-sounds/primerTones/Short8.mp3
    - available-sounds/primerTones/Short9.mp3
    - available-sounds/primerTones/Short10.mp3
    - available-sounds/primerTones/Short11.mp3
    - available-sounds/primerTones/Short12.mp3
    - available-sounds/primerTones/Short13.mp3
    - available-sounds/primerTones/Short14.mp3
    - available-sounds/primerTones/Short15.mp3
    - available-sounds/primerTones/Short16.mp3
    - available-sounds/primerTones/Short17.mp3
    - available-sounds/primerTones/Short18.mp3
    - available-sounds/primerTones/Short19.mp3
    - available-sounds/primerTones/Short20.mp3
    - available-sounds/primerTones/Short21.mp3
    - available-sounds/primerTones/Short22.mp3
    - available-sounds/primerTones/Short23.mp3
    - available-sounds/primerTones/Short24.mp3
    - available-sounds/primerTones/Short25.mp3
    - available-sounds/primerTones/Short26.mp3
    - available-sounds/primerTones/Short27.mp3
    - available-sounds/primerTones/Short28.mp3
    - available-sounds/primerTones/Short29.mp3
    - available-sounds/primerTones/Short30.mp3
    - available-sounds/primerTones/Short31.mp3
    - available-sounds/primerTones/Short32.mp3
    - available-sounds/primerTones/Short33.mp3
    - available-sounds/primerTones/Short34.mp3
    - available-sounds/primerTones/Short35.mp3
    - available-sounds/primerTones/Short36.mp3
    - available-sounds/primerTones/Short37.mp3
    - available-sounds/primerTones/Short38.mp3
    - available-sounds/primerTones/Short39.mp3
    - available-sounds/primerTones/Short40.mp3
    - available-sounds/primerTones/Short41.mp3
    - available-sounds/primerTones/Short42.mp3
    - available-sounds/primerTones/Short43.mp3
    - available-sounds/primerTones/Short44.mp3
    - available-sounds/primerTones/Short45.mp3
    - available-sounds/primerTones/Short46.mp3
    - available-sounds/primerTones/Short47.mp3
    - available-sounds/primerTones/Short48.mp3

dependency_overrides:
  win32: ^5.14.0

flutter_icons:
  android: true
  ios: false
  image_path: FlashlightsInTheDark_Icons/FlashlightsInTheDark-Icon-1024.png
